In [3]:
import pandas as pd

In [4]:
data = pd.read_excel("grants.xlsx")

In [5]:
filtered_data = data[data["აკად/მოსამზად"] == "აკად"]
filtered_data["გრანტი %"].fillna(0, inplace = True)

C:\Users\vasha\AppData\Local\Temp\ipykernel_4188\1951111908.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  filtered_data["გრანტი %"].fillna(0, inplace = True)
C:\Users\vasha\AppData\Local\Temp\ipykernel_4188\1951111908.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data["გრანტი %"].fillna(0, inplace = True)

In [7]:
filtered_data.groupby(["უსდ კოდი", "უსდ"])["გრანტი %"].mean()

უსდ კოდი  უსდ
1         სსიპ - ივანე ჯავახიშვილის სახელობის თბილისის სახელმწიფო უნივერსიტეტი                             22.518987
2         სსიპ - თბილისის ვანო სარაჯიშვილის სახელობის სახელმწიფო კონსერვატორია                              7.246377
3         სსიპ - საქართველოს ტექნიკური უნივერსიტეტი                                                         6.175926
4         სსიპ - საქართველოს შოთა რუსთაველის თეატრისა და კინოს სახელმწიფო უნივერსიტეტი                      5.304348
5         ა(ა)იპ - საქართველოს აგრარული უნივერსიტეტი                                                       44.792332
6         სსიპ - თბილისის სახელმწიფო სამედიცინო უნივერსიტეტი                                               49.346405
9         სსიპ - აკაკი წერეთლის სახელმწიფო უნივერსიტეტი                                                     4.528503
10        სსიპ - ილიას სახელმწიფო უნივერსიტეტი                                                              7.889273
12        სსიპ - სოხუმის სახელმწიფო უნივერსიტეტი                                                            0.173410
14        სსიპ - სამცხე - ჯავახეთის სახელმწიფო უნივერსიტეტი                                                 1.024590
19        შპს - ევროპის ცენტრალური უნივერსიტეტი                                                             0.000000
33        შპს - გრიგოლ რობაქიძის სახელობის უნივერსიტეტი                                                     2.148936
36        შპს - თბილისის თავისუფალი უნივერსიტეტი                                                           74.146730
40        შპს - პეტრე შოთაძის სახელობის თბილისის სამედიცინო აკადემია                                       52.580645
52        შპს - დავით ტვილდიანის სამედიცინო უნივერსიტეტი                                                   60.508475
53        სსიპ - სასწავლო უნივერსიტეტი - ბათუმის სახელმწიფო საზღვაო აკადემია                                9.055649
64        შპს - შავი ზღვის საერთაშორისო უნივერსიტეტი                                                       11.497797
71        სსიპ - იაკობ გოგებაშვილის სახელობის თელავის სახელმწიფო უნივერსიტეტი                               2.972028
85        შპს - ალტე უნივერსიტეტი                                                                           3.137931
88        შპს - სულხან-საბა ორბელიანის უნივერსიტეტი                                                         0.471698
97        სსიპ - შოთა მესხიას ზუგდიდის სახელმწიფო უნივერსიტეტი                                              1.490683
98        სსიპ - თბილისის აპოლონ ქუთათელაძის სახელობის სახელმწიფო სამხატვრო აკადემია                       18.348083
114       სსიპ - ბათუმის შოთა რუსთაველის სახელმწიფო უნივერსიტეტი                                            4.504391
115       შპს - კავკასიის საერთაშორისო უნივერსიტეტი                                                         3.231334
120       შპს - ქართულ-ამერიკული უნივერსიტეტი                                                               8.126521
121       შპს - საქართველოს უნივერსიტეტი                                                                   11.238095
122       შპს - კავკასიის უნივერსიტეტი                                                                     19.545151
129       შპს - უნივერსიტეტი გეომედი                                                                        1.162791
130       სსიპ - ბათუმის ხელოვნების სახელმწიფო უნივერსიტეტი                                                 0.892857
131       შპს - საქართველოს საავიაციო უნივერსიტეტი                                                         10.384615
133       სსიპ - გორის სახელმწიფო უნივერსიტეტი                                                              1.627297
140       შპს - ბათუმის ნავიგაციის უნივერსიტეტი                                                             0.471698
142       ა(ა)იპ "საქართველოს საპატრიარქოს წმიდა ტბელ აბუსერისძის სახელობის სასწავლო უნივერსიტეტი"          0.000000
143       შპს - „საქართველოს საერთაშორისო უნივერსიტეტი ჯიუ“                                                 0.000000
145       ა(ა)იპ - საქართველოს საპატრიარქოს წმიდა ანდრია პირველწოდებულის სახელობის ქართული უნივერსიტეტი     1.666667
152       შპს საქართველოს ეროვნული უნივერსიტეტი სეუ                                                         1.080774
153       ა(ა)იპ - ჯიპა - საქართველოს საზოგადოებრივ საქმეთა ინსტიტუტი                                      13.600000
154       ა(ა)იპ - საქართველოს საპატრიარქოს წმინდა თამარ მეფის სახელობის უნივერსიტეტი                       0.000000
155       სსიპ - დავით აღმაშენებლის სახელობის საქართველოს ეროვნული თავდაცვის აკადემია                       8.301887
171       შპს - ევროპის უნივერსიტეტი                                                                        6.067416
172       შპს აღმოსავლეთ ევროპის უნივერსიტეტი                                                               2.841530
177       ა(ა)იპ - გიორგი მთაწმინდელის სახელობის გალობის უნივერსიტეტი                                       0.000000
181       შპს „ახალი უმაღლესი სასწავლებელი-ნიუუნი“                                                          0.000000
183       ა(ა)იპ - ნიუ ვიჟენ უნივერსიტეტი                                                                  13.461538
186       სსიპ საქართველოს ფიზიკური აღზრდისა და სპორტის სახელმწიფო სასწავლო უნივერსიტეტი                    2.000000
192       შპს ბაუ ინთერნეიშენალ უნივერსითი, ბათუმი                                                         10.000000
195       შპს - ბიზნესისა და ტექნოლოგიების უნივერსიტეტი                                                    20.093819
197       სსიპ - ქუთაისის საერთაშორისო უნივერსიტეტი                                                        33.931624
198       შპს უნივერსიტეტი „ალტერბრიჯი“                                                                     1.785714
199       შპს „ბრიტანული უნივერსიტეტი“                                                                     32.222222
201       შპს - აღმოსავლეთ-დასავლეთ უნივერსიტეტი                                                            0.000000
202       ვებსტერ უნივერსიტეტის, ინკ.-ის ფილიალი საქართველოში                                              19.285714
203       შპს - კენ ვოლკერის საერთაშორისო უნივერსიტეტი                                                     50.000000
204       შპს  ,,ნეუ - ეროვნული საგანმანათლებლო უნივერსიტეტი”                                               0.000000
205       შპს - ავიცენა - ბათუმის სამედიცინო უნივერსიტეტი                                                  50.000000
206       შპს - თბილისის საერთაშორისო უნივერსიტეტი აიიუთ                                                    0.000000
Name: გრანტი %, dtype: float64

In [8]:
filtered_data.groupby(["უსდ", "პროგ. კოდი","პროგრამა"])["გრანტი %"].mean()

უსდ                                                                                        პროგ. კოდი  პროგრამა
ა(ა)იპ "საქართველოს საპატრიარქოს წმიდა ტბელ აბუსერისძის სახელობის სასწავლო უნივერსიტეტი"   14201014    ბიზნესის ადმინისტრირება (180 კრედიტი)                                                                                             0.0
                                                                                           14201015    ბიზნესის ადმინისტრირება (180 კრედიტი)                                                                                             0.0
                                                                                           14201024    ზოგადი განათლების დაწყებითი საფეხურის მასწავლებლის მომზადების ინტეგრირებული საბაკალავრო - სამაგისტრო საგანმანათლებლო პროგრამა     0.0
                                                                                           14201025    ზოგადი განათლების დაწყებითი საფეხურის მასწავლებლის მომზადების ინტეგრირებული საბაკალავრო - სამაგისტრო საგანმანათლებლო პროგრამა     0.0
                                                                                           14201035    ისტორია                                                                                                                           0.0
                                                                                                                                                                                                                                        ...
შპს „ახალი უმაღლესი სასწავლებელი-ნიუუნი“                                                   18101045    ფსიქოლოგია                                                                                                                        0.0
                                                                                           181010214   საერთაშორისო ურთიერთობები                                                                                                         0.0
შპს „ბრიტანული უნივერსიტეტი“                                                               19901014    ბიზნესი და მენეჯმენტი (ინგლისურენოვანი)                                                                                          42.5
                                                                                           19901015    ბიზნესი და მენეჯმენტი (ინგლისურენოვანი)                                                                                           0.0
                                                                                           19901045    პოლიტიკის მეცნიერება (ინგლისურენოვანი)                                                                                           60.0
Name: გრანტი %, Length: 1460, dtype: float64